<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>AvaLoader</AssemblyName>
    <RootNamespace>AvaLoader</RootNamespace>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AvaLoader.cs" />
    <Reference Include="MelonLoader">
      <HintPath>refs/MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
